Repository UBC-MDS/DSCI-522_City_of_A-Stars_310, pull requests merged in 2020-01, with the labels that each got.

#5 Project Proposal added
  README.md
Labels: documentation

#6 Solving Issue # 3
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  scripts/data_download.py
Labels: documentation

#7 Devloped EDA script
  .gitignore
  images/Place_holder_file.txt
  scripts/eda_script.py
Labels: Data-Analysis

#8 changed to ipynb
  eda/eda_students.ipynb
  scripts/eda_script.py
Labels: Data-Analysis

#9 Solving Issue #4
  scripts/data_download.py
Labels: Script Development

#11 Added link for EDA file
  README.md
Labels: documentation

#20 EDA and Cleaning scripts
  eda/eda_students.ipynb
  results/figures/placeholder.txt
  scripts/data_cleaning.py
  scripts/data_download.py
  scripts/eda_script.py
Labels: Script Development

#23 Added combined dataset, tests to eda and cleaning script, fixed index issue in grouped table
  results/math_table.csv
  results/por_table.csv
  scripts/data_cleaning.py
  scripts/eda_script.py
Labels: bug

#24 Solving Issue #15
  results/figures/distribution_mean_ci_comparison.png
  results/figures/permutation_test_comparison.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
  scripts/statistical_analysis_results.R
Labels: Script Development

#26 Added statement to address diversity and fixed typo of my name
  CODE_OF_CONDUCT.md
Labels: documentation

#30 Fixed figure labels
  doc/final_report.Rmd
  doc/final_report.html
  doc/final_report.md
Labels: bug
