Repository UBC-MDS/DSCI-522_City_of_A-Stars_310, pull requests merged in 2020-02, with the labels that each got.

#40 Makefile with clean and report rendering command
  Makefile
  README.md
Labels: Script Development

#41 Report updated with feedback
  doc/final_report.Rmd
  doc/final_report.html
  doc/final_report.md
  doc/references.bib
Labels: documentation

#44 fixed eda, cleaning scripts, updated make file
  Makefile
  eda/eda_students.ipynb
  eda/test.csv
  results/figures/distribution_mean_ci_comparison.png
  results/figures/math_plot.png
  results/figures/permutation_test_comparison.png
  results/figures/placeholder.txt
  results/figures/por_plot.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
  results/math_table.csv
  results/por_table.csv
  scripts/data_cleaning.py
  scripts/eda_script.py
Labels: Script Development, bug

#46 Fixing issue #45
  .Rhistory
  CODE_OF_CONDUCT.html
  CONTRIBUTING.html
  Makefile
Labels: Script Development

#49 Solving issues #45 #32 - Test added to download script.
  scripts/data_download.py
Labels: Script Development

#51 Fxed bugs in Makefile
  Makefile
Labels: bug

#52 updated Makefile messages
  Makefile
Labels: Script Development

#53 Solving Issue #50
  results/figures/distribution_mean_ci_comparison.png
  results/figures/permutation_test_comparison.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
  scripts/data_download.py
  scripts/statistical_analysis_results.R
Labels: Data-Analysis

#54 Removing unnecessary Code_of_conduct html file
  CODE_OF_CONDUCT.html
Labels: documentation

#56 Updated .Rmd file with edited graphs and tables
  doc/final_report.Rmd
  doc/final_report.html
  doc/final_report.md
Labels: documentation

#57 Final make all test
  Makefile
  doc/final_report.html
  doc/final_report.md
  results/figures/distribution_mean_ci_comparison.png
  results/figures/permutation_test_comparison.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
  scripts/data_download.py
Labels: Script Development

#58 Added dependency for rmarkdown
  README.md
Labels: documentation

#67 dockerfile python
  Dockerfile
  doc/final_report.html
  doc/final_report.md
  results/figures/distribution_mean_ci_comparison.png
  results/figures/math_plot.png
  results/figures/permutation_test_comparison.png
  results/figures/por_plot.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
Labels: Script Development

#69 fixed the LaTeX rendering issue
  doc/final_report.Rmd
  doc/final_report.html
  doc/final_report.md
  results/figures/distribution_mean_ci_comparison.png
  results/figures/permutation_test_comparison.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
Labels: bug

#71 Updated README with dependecy graph and instructions for reproducing results with docker
  README.md
  doc/final_report.Rmd
  doc/final_report.html
  doc/final_report.md
  doc/references.bib
Labels: documentation

#73 Added messages to docker file
  Dockerfile
  doc/final_report.html
  doc/final_report.md
  results/figures/distribution_mean_ci_comparison.png
  results/figures/math_plot.png
  results/figures/permutation_test_comparison.png
  results/figures/por_plot.png
  results/figures/result_metrics_summary.png
  results/figures/result_metrics_summary.rds
Labels: documentation
